name: chatsen
description: 3rd party client for Twitch
publish_to: 'none'
version: 1.1.87+87

environment:
  # sdk: ">=2.17.0-168.0.dev <3.0.0"
  sdk: '>=2.18.0-97.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^3.0.4
  webview_cookie_manager: ^2.0.6
  http: ^0.13.5
  web_socket_channel: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  provider: ^6.0.3
  collection: ^1.16.0
  sliver_tools: ^0.2.9
  file_picker: ^5.2.1
  json_annotation: ^4.7.0
  url_launcher: ^6.1.6
  video_player: ^2.4.7
  chewie: ^1.3.5
  wakelock: ^0.6.2
  filesize: ^2.0.1
  flutter_acrylic: ^1.0.0+2
  bitsdojo_window: ^0.1.5
  flutter_svg: ^1.1.5
  carousel_slider: ^4.1.1
  window_manager: ^0.3.2
  win32: ^3.1.4
  ffi: ^2.0.1
  flutter_localized_locales: ^2.0.4
  webview_windows: ^0.2.2
  flutter_local_notifications: ^13.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.5.1
  hive_generator: ^1.1.3
  build_runner: ^2.3.0 # flutter packages pub run build_runner build
  analyzer: any

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
