name: chatsen
description: 3rd party client for Twitch
publish_to: 'none'
version: 1.0.0+1

environment:
  # sdk: ">=2.17.0-168.0.dev <3.0.0"
  sdk: '>=2.18.0-97.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^3.0.0
  webview_cookie_manager: ^2.0.6
  http: ^0.13.4
  web_socket_channel: ^2.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  provider: ^6.0.2
  collection: ^1.15.0
  file_picker: ^4.5.0
  json_annotation: ^4.4.0
  url_launcher: ^6.0.20
  video_player: ^2.3.0
  chewie: ^1.3.2
  wakelock: ^0.6.1+2
  filesize: ^2.0.1
  flutter_acrylic: ^1.0.0+2
  bitsdojo_window: ^0.1.2
  flutter_svg: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  build_runner: ^2.1.7 # flutter packages pub run build_runner build
  analyzer: any

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
