class M3Themes {
  static Map<String, String> themes = {
    'green': '''
{
    "light": {
        "primary": "#49680e",
        "onPrimary": "#ffffff",
        "primaryContainer": "#c9f088",
        "onPrimaryContainer": "#121f00",
        "secondary": "#596248",
        "onSecondary": "#ffffff",
        "secondaryContainer": "#dde7c6",
        "onSecondaryContainer": "#171e0a",
        "tertiary": "#386661",
        "onTertiary": "#ffffff",
        "tertiaryContainer": "#bbece5",
        "onTertiaryContainer": "#00201d",
        "error": "#ba1b1b",
        "errorContainer": "#ffdad4",
        "onError": "#ffffff",
        "onErrorContainer": "#410001",
        "background": "#fdfcf4",
        "onBackground": "#1b1c18",
        "surface": "#fdfcf4",
        "onSurface": "#1b1c18",
        "surfaceVariant": "#e2e4d5",
        "onSurfaceVariant": "#45483d",
        "outline": "#75786c",
        "inverseOnSurface": "#f2f1e9",
        "inverseSurface": "#30312c"
    },
    "dark": {
        "primary": "#add36f",
        "onPrimary": "#213600",
        "primaryContainer": "#324f00",
        "onPrimaryContainer": "#c9f088",
        "secondary": "#c1cbab",
        "onSecondary": "#2b331d",
        "secondaryContainer": "#414a32",
        "onSecondaryContainer": "#dde7c6",
        "tertiary": "#a0d0c9",
        "onTertiary": "#003733",
        "tertiaryContainer": "#204e4a",
        "onTertiaryContainer": "#bbece5",
        "error": "#ffb4a9",
        "errorContainer": "#930006",
        "onError": "#680003",
        "onErrorContainer": "#ffdad4",
        "background": "#1b1c18",
        "onBackground": "#e4e3db",
        "surface": "#1b1c18",
        "onSurface": "#e4e3db",
        "surfaceVariant": "#45483d",
        "onSurfaceVariant": "#c5c8b9",
        "outline": "#8f9284",
        "inverseOnSurface": "#1b1c18",
        "inverseSurface": "#e4e3db"
    },
    "primary": {
        "luminance100": "#ffffff",
        "luminance99": "#f9ffe1",
        "luminance98": "#f1ffce",
        "luminance95": "#d6fe94",
        "luminance90": "#c9f088",
        "luminance80": "#add36f",
        "luminance70": "#93b757",
        "luminance60": "#799c3f",
        "luminance50": "#608127",
        "luminance40": "#49680e",
        "luminance35": "#3d5b00",
        "luminance30": "#324f00",
        "luminance25": "#294200",
        "luminance20": "#213600",
        "luminance10": "#121f00",
        "luminance0": "#000000"
    },
    "secondary": {
        "luminance100": "#ffffff",
        "luminance99": "#f9ffe1",
        "luminance98": "#f4fedc",
        "luminance95": "#ecf5d5",
        "luminance90": "#dde7c6",
        "luminance80": "#c1cbab",
        "luminance70": "#a6af92",
        "luminance60": "#8b9478",
        "luminance50": "#717a5f",
        "luminance40": "#596248",
        "luminance35": "#4d563d",
        "luminance30": "#414a32",
        "luminance25": "#363e28",
        "luminance20": "#2b331d",
        "luminance10": "#171e0a",
        "luminance0": "#000000"
    },
    "tertiary": {
        "luminance100": "#ffffff",
        "luminance99": "#effffd",
        "luminance98": "#e1fffb",
        "luminance95": "#cafbf4",
        "luminance90": "#bbece5",
        "luminance80": "#a0d0c9",
        "luminance70": "#85b4ae",
        "luminance60": "#6b9993",
        "luminance50": "#527f7a",
        "luminance40": "#386661",
        "luminance35": "#2c5a55",
        "luminance30": "#204e4a",
        "luminance25": "#11423e",
        "luminance20": "#003733",
        "luminance10": "#00201d",
        "luminance0": "#000000"
    },
    "neutral": {
        "luminance100": "#ffffff",
        "luminance99": "#fdfcf4",
        "luminance98": "#faf9f1",
        "luminance95": "#f2f1e9",
        "luminance90": "#e4e3db",
        "luminance80": "#c7c7bf",
        "luminance70": "#acaca5",
        "luminance60": "#91918a",
        "luminance50": "#777771",
        "luminance40": "#5e5f59",
        "luminance35": "#52534d",
        "luminance30": "#464741",
        "luminance25": "#3b3c37",
        "luminance20": "#30312c",
        "luminance10": "#1b1c18",
        "luminance0": "#000000"
    },
    "neutralVariant": {
        "luminance100": "#ffffff",
        "luminance99": "#fbfeed",
        "luminance98": "#f9fbeb",
        "luminance95": "#f0f2e3",
        "luminance90": "#e2e4d5",
        "luminance80": "#c5c8b9",
        "luminance70": "#aaad9e",
        "luminance60": "#8f9284",
        "luminance50": "#75786c",
        "luminance40": "#5d6054",
        "luminance35": "#515449",
        "luminance30": "#45483d",
        "luminance25": "#3a3d33",
        "luminance20": "#2f3228",
        "luminance10": "#1a1d14",
        "luminance0": "#000000"
    },
    "error": {
        "luminance100": "#ffffff",
        "luminance99": "#fcfcfc",
        "luminance98": "#fff8f6",
        "luminance95": "#ffede9",
        "luminance90": "#ffdad4",
        "luminance80": "#ffb4a9",
        "luminance70": "#ff897a",
        "luminance60": "#ff5449",
        "luminance50": "#dd3730",
        "luminance40": "#ba1b1b",
        "luminance35": "#a8060f",
        "luminance30": "#930006",
        "luminance25": "#7d0004",
        "luminance20": "#680003",
        "luminance10": "#410001",
        "luminance0": "#000000"
    },
    "styles": {
        "display1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 64,
            "lineHeight": 76,
            "letterSpacing": -0.5,
            "paragraphSpacing": 0
        },
        "display2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 57,
            "lineHeight": 64,
            "letterSpacing": -0.25,
            "paragraphSpacing": 0
        },
        "display3": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 45,
            "lineHeight": 52,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 36,
            "lineHeight": 44,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 32,
            "lineHeight": 40,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline3": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 28,
            "lineHeight": 36,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline4": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 24,
            "lineHeight": 32,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline5": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 22,
            "lineHeight": 28,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline6": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 18,
            "lineHeight": 24,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "subhead1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 16,
            "lineHeight": 24,
            "letterSpacing": 0.1,
            "paragraphSpacing": 0
        },
        "subhead2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 14,
            "lineHeight": 20,
            "letterSpacing": 0.1,
            "paragraphSpacing": 0
        },
        "button": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 14,
            "lineHeight": 20,
            "letterSpacing": 0.1,
            "paragraphSpacing": 0
        },
        "body1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 16,
            "lineHeight": 24,
            "letterSpacing": 0.5,
            "paragraphSpacing": 0
        },
        "body2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 14,
            "lineHeight": 20,
            "letterSpacing": 0.25,
            "paragraphSpacing": 0
        },
        "caption": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 12,
            "lineHeight": 16,
            "letterSpacing": 0.4,
            "paragraphSpacing": 0
        },
        "overline": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 12,
            "lineHeight": 16,
            "letterSpacing": 0.5,
            "paragraphSpacing": 0
        },
        "labelSmall": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 11,
            "lineHeight": 16,
            "letterSpacing": 0.5,
            "paragraphSpacing": 0
        }
    },
    "source": {
        "seed": "#8d9976",
        "imageUrl": "assets/5_wallpaper.webp",
        "primary": "#49680e",
        "secondary": "#596248",
        "tertiary": "#386661",
        "neutral": "#5e5f59",
        "neutralVariant": "#5d6054",
        "error": "#ba1b1b"
    }
}
    ''',
    'itto': '''
{
    "light": {
        "primary": "#8f4e00",
        "onPrimary": "#ffffff",
        "primaryContainer": "#ffdcbf",
        "onPrimaryContainer": "#2e1500",
        "secondary": "#745943",
        "onSecondary": "#ffffff",
        "secondaryContainer": "#ffdcc0",
        "onSecondaryContainer": "#2a1707",
        "tertiary": "#5b6238",
        "onTertiary": "#ffffff",
        "tertiaryContainer": "#dfe7b2",
        "onTertiaryContainer": "#181e00",
        "error": "#ba1b1b",
        "errorContainer": "#ffdad4",
        "onError": "#ffffff",
        "onErrorContainer": "#410001",
        "background": "#fcfcfc",
        "onBackground": "#201a16",
        "surface": "#fcfcfc",
        "onSurface": "#201a16",
        "surfaceVariant": "#f3dfd1",
        "onSurfaceVariant": "#51443a",
        "outline": "#837469",
        "inverseOnSurface": "#faeee7",
        "inverseSurface": "#352f2b"
    },
    "dark": {
        "primary": "#ffb775",
        "onPrimary": "#4d2700",
        "primaryContainer": "#6d3a00",
        "onPrimaryContainer": "#ffdcbf",
        "secondary": "#e3c0a5",
        "onSecondary": "#412c19",
        "secondaryContainer": "#5a422d",
        "onSecondaryContainer": "#ffdcc0",
        "tertiary": "#c3cb98",
        "onTertiary": "#2d330e",
        "tertiaryContainer": "#434a22",
        "onTertiaryContainer": "#dfe7b2",
        "error": "#ffb4a9",
        "errorContainer": "#930006",
        "onError": "#680003",
        "onErrorContainer": "#ffdad4",
        "background": "#201a16",
        "onBackground": "#ece0d9",
        "surface": "#201a16",
        "onSurface": "#ece0d9",
        "surfaceVariant": "#51443a",
        "onSurfaceVariant": "#d6c3b6",
        "outline": "#9e8d81",
        "inverseOnSurface": "#201a16",
        "inverseSurface": "#ece0d9"
    },
    "primary": {
        "luminance100": "#ffffff",
        "luminance99": "#fcfcfc",
        "luminance98": "#fff8f3",
        "luminance95": "#ffeddf",
        "luminance90": "#ffdcbf",
        "luminance80": "#ffb775",
        "luminance70": "#ee9743",
        "luminance60": "#ce7d2b",
        "luminance50": "#b06511",
        "luminance40": "#8f4e00",
        "luminance35": "#7e4400",
        "luminance30": "#6d3a00",
        "luminance25": "#5d3000",
        "luminance20": "#4d2700",
        "luminance10": "#2e1500",
        "luminance0": "#000000"
    },
    "secondary": {
        "luminance100": "#ffffff",
        "luminance99": "#fcfcfc",
        "luminance98": "#fff8f3",
        "luminance95": "#ffeddf",
        "luminance90": "#ffdcc0",
        "luminance80": "#e3c0a5",
        "luminance70": "#c6a58b",
        "luminance60": "#aa8b72",
        "luminance50": "#8e715a",
        "luminance40": "#745943",
        "luminance35": "#664d38",
        "luminance30": "#5a422d",
        "luminance25": "#4e3723",
        "luminance20": "#412c19",
        "luminance10": "#2a1707",
        "luminance0": "#000000"
    },
    "tertiary": {
        "luminance100": "#ffffff",
        "luminance99": "#fbffd7",
        "luminance98": "#f6fec7",
        "luminance95": "#eef6bf",
        "luminance90": "#dfe7b2",
        "luminance80": "#c3cb98",
        "luminance70": "#a8b07e",
        "luminance60": "#8d9565",
        "luminance50": "#737b4e",
        "luminance40": "#5b6238",
        "luminance35": "#4f562d",
        "luminance30": "#434a22",
        "luminance25": "#383f18",
        "luminance20": "#2d330e",
        "luminance10": "#181e00",
        "luminance0": "#000000"
    },
    "neutral": {
        "luminance100": "#ffffff",
        "luminance99": "#fcfcfc",
        "luminance98": "#fff8f3",
        "luminance95": "#faeee7",
        "luminance90": "#ece0d9",
        "luminance80": "#cfc4bd",
        "luminance70": "#b3a9a3",
        "luminance60": "#988f89",
        "luminance50": "#7e7670",
        "luminance40": "#655d58",
        "luminance35": "#58514c",
        "luminance30": "#4c4540",
        "luminance25": "#413a35",
        "luminance20": "#352f2b",
        "luminance10": "#201a16",
        "luminance0": "#000000"
    },
    "neutralVariant": {
        "luminance100": "#ffffff",
        "luminance99": "#fcfcfc",
        "luminance98": "#fff8f3",
        "luminance95": "#ffede0",
        "luminance90": "#f3dfd1",
        "luminance80": "#d6c3b6",
        "luminance70": "#b9a89c",
        "luminance60": "#9e8d81",
        "luminance50": "#837469",
        "luminance40": "#6a5c51",
        "luminance35": "#5d5046",
        "luminance30": "#51443a",
        "luminance25": "#453930",
        "luminance20": "#3a2e25",
        "luminance10": "#231a12",
        "luminance0": "#000000"
    },
    "error": {
        "luminance100": "#ffffff",
        "luminance99": "#fcfcfc",
        "luminance98": "#fff8f6",
        "luminance95": "#ffede9",
        "luminance90": "#ffdad4",
        "luminance80": "#ffb4a9",
        "luminance70": "#ff897a",
        "luminance60": "#ff5449",
        "luminance50": "#dd3730",
        "luminance40": "#ba1b1b",
        "luminance35": "#a8060f",
        "luminance30": "#930006",
        "luminance25": "#7d0004",
        "luminance20": "#680003",
        "luminance10": "#410001",
        "luminance0": "#000000"
    },
    "styles": {
        "display1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 64,
            "lineHeight": 76,
            "letterSpacing": -0.5,
            "paragraphSpacing": 0
        },
        "display2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 57,
            "lineHeight": 64,
            "letterSpacing": -0.25,
            "paragraphSpacing": 0
        },
        "display3": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 45,
            "lineHeight": 52,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 36,
            "lineHeight": 44,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 32,
            "lineHeight": 40,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline3": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 28,
            "lineHeight": 36,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline4": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 24,
            "lineHeight": 32,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline5": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 22,
            "lineHeight": 28,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline6": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 18,
            "lineHeight": 24,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "subhead1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 16,
            "lineHeight": 24,
            "letterSpacing": 0.1,
            "paragraphSpacing": 0
        },
        "subhead2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 14,
            "lineHeight": 20,
            "letterSpacing": 0.1,
            "paragraphSpacing": 0
        },
        "button": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 14,
            "lineHeight": 20,
            "letterSpacing": 0.1,
            "paragraphSpacing": 0
        },
        "body1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 16,
            "lineHeight": 24,
            "letterSpacing": 0.5,
            "paragraphSpacing": 0
        },
        "body2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 14,
            "lineHeight": 20,
            "letterSpacing": 0.25,
            "paragraphSpacing": 0
        },
        "caption": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 12,
            "lineHeight": 16,
            "letterSpacing": 0.4,
            "paragraphSpacing": 0
        },
        "overline": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 12,
            "lineHeight": 16,
            "letterSpacing": 0.5,
            "paragraphSpacing": 0
        },
        "labelSmall": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 11,
            "lineHeight": 16,
            "letterSpacing": 0.5,
            "paragraphSpacing": 0
        }
    },
    "source": {
        "seed": "#966334",
        "imageUrl": "blob:https://material-foundation.github.io/1297a4cd-45ec-4547-9738-79324356e261",
        "primary": "#8f4e00",
        "secondary": "#745943",
        "tertiary": "#5b6238",
        "neutral": "#655d58",
        "neutralVariant": "#6a5c51",
        "error": "#ba1b1b"
    }
}
    ''',
    'blue': '''
    {
    "light": {
        "primary": "#006c48",
        "onPrimary": "#ffffff",
        "primaryContainer": "#8bf8c4",
        "onPrimaryContainer": "#002113",
        "secondary": "#4d6357",
        "onSecondary": "#ffffff",
        "secondaryContainer": "#cfe8d8",
        "onSecondaryContainer": "#0a1f16",
        "tertiary": "#3d6473",
        "onTertiary": "#ffffff",
        "tertiaryContainer": "#c1e9fb",
        "onTertiaryContainer": "#001f29",
        "error": "#ba1b1b",
        "errorContainer": "#ffdad4",
        "onError": "#ffffff",
        "onErrorContainer": "#410001",
        "background": "#fbfdf8",
        "onBackground": "#191c1a",
        "surface": "#fbfdf8",
        "onSurface": "#191c1a",
        "surfaceVariant": "#dce5dd",
        "onSurfaceVariant": "#404943",
        "outline": "#707973",
        "inverseOnSurface": "#eff1ed",
        "inverseSurface": "#2d312e"
    },
    "dark": {
        "primary": "#6edba9",
        "onPrimary": "#003823",
        "primaryContainer": "#005236",
        "onPrimaryContainer": "#8bf8c4",
        "secondary": "#b3ccbc",
        "onSecondary": "#1f352a",
        "secondaryContainer": "#364b40",
        "onSecondaryContainer": "#cfe8d8",
        "tertiary": "#a5cdde",
        "onTertiary": "#063543",
        "tertiaryContainer": "#244c5b",
        "onTertiaryContainer": "#c1e9fb",
        "error": "#ffb4a9",
        "errorContainer": "#930006",
        "onError": "#680003",
        "onErrorContainer": "#ffdad4",
        "background": "#191c1a",
        "onBackground": "#e1e3df",
        "surface": "#191c1a",
        "onSurface": "#e1e3df",
        "surfaceVariant": "#404943",
        "onSurfaceVariant": "#bfc9c1",
        "outline": "#8a938c",
        "inverseOnSurface": "#191c1a",
        "inverseSurface": "#e1e3df"
    },
    "primary": {
        "luminance100": "#ffffff",
        "luminance99": "#f2fff6",
        "luminance98": "#e6fff0",
        "luminance95": "#bcffdd",
        "luminance90": "#8bf8c4",
        "luminance80": "#6edba9",
        "luminance70": "#51be8f",
        "luminance60": "#31a376",
        "luminance50": "#00885e",
        "luminance40": "#006c48",
        "luminance35": "#005f3f",
        "luminance30": "#005236",
        "luminance25": "#00452c",
        "luminance20": "#003823",
        "luminance10": "#002113",
        "luminance0": "#000000"
    },
    "secondary": {
        "luminance100": "#ffffff",
        "luminance99": "#f2fff6",
        "luminance98": "#e7ffef",
        "luminance95": "#ddf7e6",
        "luminance90": "#cfe8d8",
        "luminance80": "#b3ccbc",
        "luminance70": "#99b1a2",
        "luminance60": "#7f9688",
        "luminance50": "#667c6f",
        "luminance40": "#4d6357",
        "luminance35": "#41574b",
        "luminance30": "#364b40",
        "luminance25": "#2b4035",
        "luminance20": "#1f352a",
        "luminance10": "#0a1f16",
        "luminance0": "#000000"
    },
    "tertiary": {
        "luminance100": "#ffffff",
        "luminance99": "#f9fdff",
        "luminance98": "#f2fbff",
        "luminance95": "#ddf5ff",
        "luminance90": "#c1e9fb",
        "luminance80": "#a5cdde",
        "luminance70": "#8ab1c2",
        "luminance60": "#6f96a6",
        "luminance50": "#567c8c",
        "luminance40": "#3d6473",
        "luminance35": "#305766",
        "luminance30": "#244c5b",
        "luminance25": "#17404f",
        "luminance20": "#063543",
        "luminance10": "#001f29",
        "luminance0": "#000000"
    },
    "neutral": {
        "luminance100": "#ffffff",
        "luminance99": "#fbfdf8",
        "luminance98": "#f8faf6",
        "luminance95": "#eff1ed",
        "luminance90": "#e1e3df",
        "luminance80": "#c5c7c3",
        "luminance70": "#a9aca8",
        "luminance60": "#8f918e",
        "luminance50": "#757875",
        "luminance40": "#5c5f5c",
        "luminance35": "#505350",
        "luminance30": "#444845",
        "luminance25": "#383c39",
        "luminance20": "#2d312e",
        "luminance10": "#191c1a",
        "luminance0": "#000000"
    },
    "neutralVariant": {
        "luminance100": "#ffffff",
        "luminance99": "#f5fef6",
        "luminance98": "#f2fcf3",
        "luminance95": "#eaf3eb",
        "luminance90": "#dce5dd",
        "luminance80": "#bfc9c1",
        "luminance70": "#a4ada6",
        "luminance60": "#8a938c",
        "luminance50": "#707973",
        "luminance40": "#58605a",
        "luminance35": "#4c554f",
        "luminance30": "#404943",
        "luminance25": "#353d38",
        "luminance20": "#2a322d",
        "luminance10": "#151d18",
        "luminance0": "#000000"
    },
    "error": {
        "luminance100": "#ffffff",
        "luminance99": "#fcfcfc",
        "luminance98": "#fff8f6",
        "luminance95": "#ffede9",
        "luminance90": "#ffdad4",
        "luminance80": "#ffb4a9",
        "luminance70": "#ff897a",
        "luminance60": "#ff5449",
        "luminance50": "#dd3730",
        "luminance40": "#ba1b1b",
        "luminance35": "#a8060f",
        "luminance30": "#930006",
        "luminance25": "#7d0004",
        "luminance20": "#680003",
        "luminance10": "#410001",
        "luminance0": "#000000"
    },
    "styles": {
        "display1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 64,
            "lineHeight": 76,
            "letterSpacing": -0.5,
            "paragraphSpacing": 0
        },
        "display2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 57,
            "lineHeight": 64,
            "letterSpacing": -0.25,
            "paragraphSpacing": 0
        },
        "display3": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 45,
            "lineHeight": 52,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 36,
            "lineHeight": 44,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 32,
            "lineHeight": 40,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline3": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 28,
            "lineHeight": 36,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline4": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 24,
            "lineHeight": 32,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline5": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 22,
            "lineHeight": 28,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "headline6": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 18,
            "lineHeight": 24,
            "letterSpacing": 0,
            "paragraphSpacing": 0
        },
        "subhead1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 16,
            "lineHeight": 24,
            "letterSpacing": 0.1,
            "paragraphSpacing": 0
        },
        "subhead2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 14,
            "lineHeight": 20,
            "letterSpacing": 0.1,
            "paragraphSpacing": 0
        },
        "button": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 14,
            "lineHeight": 20,
            "letterSpacing": 0.1,
            "paragraphSpacing": 0
        },
        "body1": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 16,
            "lineHeight": 24,
            "letterSpacing": 0.5,
            "paragraphSpacing": 0
        },
        "body2": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 14,
            "lineHeight": 20,
            "letterSpacing": 0.25,
            "paragraphSpacing": 0
        },
        "caption": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Regular",
            "fontSize": 12,
            "lineHeight": 16,
            "letterSpacing": 0.4,
            "paragraphSpacing": 0
        },
        "overline": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 12,
            "lineHeight": 16,
            "letterSpacing": 0.5,
            "paragraphSpacing": 0
        },
        "labelSmall": {
            "fontFamilyName": "Roboto",
            "fontFamilyStyle": "Medium",
            "fontSize": 11,
            "lineHeight": 16,
            "letterSpacing": 0.5,
            "paragraphSpacing": 0
        }
    },
    "source": {
        "seed": "#849f8f",
        "imageUrl": "assets/2_wallpaper.webp",
        "primary": "#006c48",
        "secondary": "#4d6357",
        "tertiary": "#3d6473",
        "neutral": "#5c5f5c",
        "neutralVariant": "#58605a",
        "error": "#ba1b1b"
    }
}
    ''',
  };
}
